name: lucienengelen
favicon: null
layout_spectrum: 0.4903482540976256
typography_spectrum: 0.041013503447175026
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.37150821345858276
  lightness: 0.25973071716725826
  saturation: 0.8510800318326801
  rhythmicContrast: 0.9396109122317284
purpose: []
