name: lucienengelen
favicon: null
layout_spectrum: 0.26031
typography_spectrum: 0.74828
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070607'
    - '#f9f9f9'
    - '#af9248'
    - '#7b6c5d'
    - '#3e372e'
  brandStrength: 0.5
  lightness: 0.0625
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
