name: lucienengelen
favicon: null
layout_spectrum: 0.26031
typography_spectrum: 0.041013503447175026
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#aeb1a3'
    - '#364d4e'
    - '#fbfbf9'
    - '#6f7f7b'
  brandStrength: 0.5
  lightness: 0.0625
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
